package Modelo.Enums;

public enum Evento {
    DESCARTAR_CARTA, ACTUALIZAR_HERRAMIENTAS, JUGAR_CARTA_TABLERO, TOMAR_CARTA, PASAR_TURNO, NUEVO_USUARIO, INICIAR_PARTIDA, NUEVA_RONDA_GANADOR_MINEROS, NUEVA_RONDA_GANADOR_SABOTEADORES, FINALIZAR_PARTIDA_MINEROS, CARGAR_PARTIDA, INICIAR_PARTIDA_CARGADA, SERVIDOR_NOTIFICA_CLIENTE, FINALIZAR_PARTIDA_SABOTEADORES
}
