package Modelo.Enums;

public enum TipoAccion {
    ROMPERPICO, ROMPERLINTERNA, ROMPERVAGONETA,
    DERRUMBAR, REPARARPICO, REPARARVAGONETA, REPARARLINTERNA, OBJETIVO_REPARAR_PICO, OBJETIVO_ROMPER_PICO, MAPA
}
